name:  Test Pipeline
on:
  push:
    branches:
    -  main
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  test:
    runs-on:  ubuntu-latest
    env:
      SELAMLAMA: Hello

    steps:
    -  name: Osman Env Tanimlama
       run: |
        echo "Hello World"
        echo "$DAY_OF_WEEK"
        env:
          OSMAN : "Bu osman bizim osman bu adimda tanimlandi" 
      
